### ISSUE TITLE
🎨  Create account page visual issues

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#29]
**Describe the bug**
On the create account page there are 2 visual bugs
1. The left blue side bar containing text only covers the visual part of the screen. -> if you scroll down it stops
2. The width of the google login button is faulty

![image](https://user-images.githubusercontent.com/122394075/212725016-34b76612-7790-492e-84d8-9c14dc3f3766.png)

**To Reproduce**
1. Go to https://kujali-1be70.web.app/auth/login
4. scroll down

**Comment by IanOdhiambo9** [comment]
Fixed
