### ISSUE TITLE
🎨  Create account page - No feedback about the requirements of the password

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#30]
**Describe the bug**
When you want to create an account with the password "Test", the spinner on the screen just keeps on spinning forever.
If you use the password "Test123", he does create the new account.

**Expected behavior**
Show an error message indicating what is/went wrong when trying to create an account

**Screenshots**
![image](https://user-images.githubusercontent.com/122394075/212725745-3748c11c-dda5-4872-9903-ef7ccf73b1c4.png)

**Comment by IanOdhiambo9** [comment]
Now the button is disabled if the passwords don't match
