### ISSUE TITLE
🎨  Create account page - no error when re-creating account

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#31]
**Describe the bug**
When you try to create an account for an email address that already has an account, the only thing you see is the spinner that keeps spinning.

There are no other indications that it is not possible to create the account (for whatever reason)

**Expected behavior**
Indicate that an account with this email address already exists.

**Comment by M-ikkels** [comment]
@jrosseel don't know what the security guidelines are exactly for this type of issue. If you say that the email address is already in use, this provide potential hackers with extra information about the system.

**Comment by IanOdhiambo9** [comment]
Fixed
