### ISSUE TITLE
🎨 Current year not filled in correctly

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#33]
**Describe the bug**
When opening the budget page, the current year is filled in with 2022 instead of 2023

**To Reproduce**
Open the budget page
+ switch tabs Montly / quarterly / yearly

**Expected behavior**
Current year is filled in with 2023

**Screenshots**
![image](https://user-images.githubusercontent.com/122394075/214120220-a651085b-9c55-41fb-98be-cac77ff5e418.png)

**Comment by IanOdhiambo9** [comment]
Has been fixed.
