### ISSUE TITLE
🎨 Start date of an income should be set to the current year by default

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#34]
**Describe the bug**
Start date of an income should be set to the current year by default

**To Reproduce**
open a budget
add an income
**Expected behavior**
start date is by default the current year

**Screenshots**
![image](https://user-images.githubusercontent.com/122394075/214121035-3a52fb3a-1658-46b9-9988-72974838d441.png)

**Comment by IanOdhiambo9** [comment]
Set to current year
