### ISSUE TITLE
🎨 income/cost in budget is not save

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#35]
Same for income and cost

**To Reproduce**
Open a budget
add an income
![image](https://user-images.githubusercontent.com/122394075/214122040-facd4c92-31c0-479b-886d-46549c43eeed.png)
Create after this step
![image](https://user-images.githubusercontent.com/122394075/214122266-28dbfb9f-7004-40f0-b504-772151b8c6c0.png)

Go to page "expenses"
Go back to budgets
Edit budget
The line that was here is now gone:
![image](https://user-images.githubusercontent.com/122394075/214122205-8e81a407-f163-4750-b08e-12460b8107b6.png)

**Expected behavior**
Income line is still present when re-editing the budget

**Comment by IanOdhiambo9** [comment]
A submit budget button has been added that now allows the user to save their changes.
