### ISSUE TITLE
🎨  creating new expenses does nothing

### ISSUE THREAD

**Issue by M-ikkels** [italanta/kujali#36]
**Describe the bug**
when trying to create a new expense via the "expense" menu, nothing happens
![image](https://user-images.githubusercontent.com/122394075/214123438-ad342b0b-450d-47f5-a608-8bbf4c10e1c8.png)

**Expected behavior**
??

**Comment by IanOdhiambo9** [comment]
Expense allocs has now been added for activated budgets
