### ISSUE TITLE
🎨 [Redesign of Budgeting page] create a table with clear descriptions

### ISSUE THREAD

**Issue by tedmwatha** [italanta/kujali#48]
**As a user I cannot differentiate the active budget from the non active one.**

A table will be able to tabulate the information in a more descriptive and detailed way

![Screenshot 2023-05-23 at 12 26 27 (2)](https://github.com/italanta/kujali/assets/131648555/d1df886e-311a-415e-b9bb-4d7c0550db50)

**I would like a table design**

It will highlight if a budget is activated and the duration of time as well as the intended timelines.
Drop downs will help the user see what child budgets are linked to the parent one .

![image](https://github.com/italanta/kujali/assets/131648555/e80a4ce2-8e28-4662-8aec-cd8e755a6731)

**Comment by IanOdhiambo9** [comment]
Done!
