### ISSUE TITLE
🎨 [Add Item button] on the invoice creation page 

### ISSUE THREAD

**Issue by tedmwatha** [italanta/kujali#53]
**make the add item button well defined.**
As a user I would like to be able to add items without having to look for the add item option. Int currently doesn't look very intuitive at the moment as it is not a button 
<img width="1440" alt="Screenshot 2023-05-11 at 16 56 11" src="https://github.com/italanta/kujali/assets/131648555/68ff0ed7-3c22-48f2-9fb4-1107fd9ddc98">

**Creating a button will be a very simple solution**
![Group 19](https://github.com/italanta/kujali/assets/131648555/5836a1e9-c1b3-4487-a08d-0845dbeec5ed)

**Comment by IanOdhiambo9** [comment]
Done!
