### ISSUE TITLE
🎨 [Fix Call to action buttons in Invoice] 

### ISSUE THREAD

**Issue by tedmwatha** [italanta/kujali#54]
**When creating an invoice I can lose information if I don't save the progress**
One has to keep saving the progress so as not to lose data and the buttons for performing the same are at the top yet one adds items in an invoice at the bottom.

<img width="1440" alt="Screenshot 2023-05-11 at 17 00 46" src="https://github.com/italanta/kujali/assets/131648555/c2343eef-851a-4165-b69f-b03213759657">

**I would like the buttons to be available at the top and bottom **
This can be done by either have them remain static on the side they are already on or have others at the bottom of the invoice.

![Frame](https://github.com/italanta/kujali/assets/131648555/1d0c6eaa-b917-4ada-8de4-5a68c0d1fafb)

**Comment by IanOdhiambo9** [comment]
Done!
