### ISSUE TITLE
🎨 [Login button] At login there is no button

### ISSUE THREAD

**Issue by tedmwatha** [italanta/kujali#57]
**There is no Login call to action **
When I go to login to my kujali account and input my login details the only button available is remember me

<img width="1440" alt="Screenshot 2023-05-30 at 10 12 30" src="https://github.com/italanta/kujali/assets/131648555/a6ab0d2d-6aad-4fd1-a72b-c0080933d550">

**Remember me should be a check box **
Instead of a button saying remember me let it be a check box and make the button for logging in 

![login](https://github.com/italanta/kujali/assets/131648555/816b3d9b-6f91-47c1-a007-7861dc377873)

**Comment by IanOdhiambo9** [comment]
Fixed
