### ISSUE TITLE
🎨 Create New Expense modal does not close automatically after creating an expense

### ISSUE THREAD

**Issue by Salemukuri** [italanta/kujali#63]
**Describe the bug**
The Create New Expense modal on the Expenses page does not close automatically after a new expense has been created, and remains populated with data of the just created expense. Consequently, users can inadvertently create duplicate expenses by repeatedly clicking the 'Create New Expense' button without realizing that the expense has already been created.

**To Reproduce**
1. Go to Expenses
2. Add a new expense
3. Click on 'Create New Expense' button to add the expense
4. A new line of expense is added but the modal does not close automatically, and remains populated with the data you just entered

**Expected behavior**
The modal should be programmed to close automatically upon successful submission of an expense, while also resetting the form fields to prepare for a new entry - for convenience and to avoid unintentional duplication of expenses

**Screenshots**
![Frame 8](https://github.com/italanta/kujali/assets/65705753/6daec934-3a0c-4f26-953a-1814d7395e8c)

**Comment by IanOdhiambo9** [comment]
Fixed
